CREATE TABLE MJESTO 
(
  PBR NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(50) NOT NULL 
, CONSTRAINT MJESTO_PK PRIMARY KEY (PBR) ENABLE 
);


CREATE TABLE RANGSUCA 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(20) NOT NULL 
, CONSTRAINT RANGSUCA_PK PRIMARY KEY (ID) ENABLE 
);


CREATE TABLE ULOGASUCA 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(50) NOT NULL 
, CONSTRAINT ULOGASUCA_PK PRIMARY KEY (ID) ENABLE 
);

CREATE TABLE KLUB 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(50) NOT NULL 
, CONSTRAINT KLUB_PK PRIMARY KEY (ID) ENABLE 
);


CREATE TABLE VRSTAEKIPE 
(
  ID NUMBER(10) NOT NULL 
, UZRAST VARCHAR2(20) NOT NULL 
, SPOL VARCHAR2(10) NOT NULL 
, CONSTRAINT VRSTAEKIPE_PK PRIMARY KEY (ID) ENABLE 
);


CREATE TABLE EKIPA 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(50) 
, ID_VRSTA NUMBER(10) NOT NULL 
, ID_KLUB NUMBER(10) NOT NULL 
, CONSTRAINT EKIPA_PK PRIMARY KEY (ID) ENABLE 
, CONSTRAINT FK_VRSTA_EKIPA FOREIGN KEY (ID_VRSTA) REFERENCES VRSTAEKIPE (ID)
, CONSTRAINT FK_KLUB_EKIPA FOREIGN KEY (ID_KLUB) REFERENCES KLUB (ID)
);


CREATE TABLE NATJECANJE 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(50) NOT NULL 
, DATUM_POCETKA DATE 
, DATUM_ZAVRSETKA DATE 
, SEZONA VARCHAR2(15) NOT NULL 
, ID_VRSTA NUMBER(10) NOT NULL 
, CONSTRAINT NATJECANJE_PK PRIMARY KEY (ID) ENABLE 
, CONSTRAINT FK_VRSTA_NATJECANJE FOREIGN KEY (ID_VRSTA) REFERENCES VRSTAEKIPE (ID)
);


CREATE TABLE UTAKMICA 
(
  ID NUMBER(10) NOT NULL 
, DATUM DATE NOT NULL 
, ID_NATJECANJE NUMBER(10) NOT NULL 
, ID_DOMACINI NUMBER(10) NOT NULL 
, ID_GOSTI NUMBER(10) NOT NULL 
, CONSTRAINT UTAKMICA_PK PRIMARY KEY (ID) ENABLE 
, CONSTRAINT FK_NATJECANJE_UTAKMICA FOREIGN KEY (ID_NATJECANJE) REFERENCES NATJECANJE (ID)
, CONSTRAINT FK_DOMACINI_UTAKMICA FOREIGN KEY (ID_DOMACINI) REFERENCES EKIPA (ID)
, CONSTRAINT FK_GOSTI_UTAKMICA FOREIGN KEY (ID_GOSTI) REFERENCES EKIPA (ID)
);


CREATE TABLE SUDAC 
(
  ID NUMBER(10) NOT NULL 
, IME VARCHAR2(50) NOT NULL 
, PREZIME VARCHAR2(50) NOT NULL 
, DATUM_RODENJA DATE NOT NULL 
, TELEFON VARCHAR2(20) 
, ADRESA VARCHAR2(50) NOT NULL 
, ID_RANG NUMBER(10) NOT NULL 
, PBR_STANOVANJA NUMBER(10) 
, PBR_RODJENJA NUMBER(10) 
, CONSTRAINT SUDAC_PK PRIMARY KEY (ID) ENABLE 
, CONSTRAINT FK_RANG_SUDAC FOREIGN KEY (ID_RANG) REFERENCES RANGSUCA (ID)
, CONSTRAINT FK_PBR_STANOVANJA_SUDAC FOREIGN KEY (PBR_STANOVANJA) REFERENCES MJESTO(PBR)
, CONSTRAINT FK_PBR_RODJENJA_SUDAC FOREIGN KEY (PBR_RODJENJA) REFERENCES MJESTO(PBR)
);


CREATE TABLE LISTA 
(
  ID_SUDAC NUMBER NOT NULL 
, ID_NATJECANJE NUMBER NOT NULL 
, CONSTRAINT LISTA_PK PRIMARY KEY (ID_SUDAC, ID_NATJECANJE) ENABLE
, CONSTRAINT FK_SUDAC_LISTA FOREIGN KEY (ID_SUDAC) REFERENCES SUDAC (ID)
, CONSTRAINT FK_NATJECANJE_LISTA FOREIGN KEY (ID_NATJECANJE) REFERENCES NATJECANJE (ID)
);


CREATE TABLE SUDENJE 
(
  ID_UTAKMICA NUMBER(10) NOT NULL 
, ID_SUDAC NUMBER(10) NOT NULL 
, ID_ULOGA NUMBER(10) NOT NULL 
, OCJENA NUMBER CONSTRAINT OCJENA_CK CHECK (OCJENA >= 0 AND OCJENA<=100)
, CONSTRAINT SUDENJE_PK PRIMARY KEY (ID_UTAKMICA , ID_SUDAC) ENABLE 
, CONSTRAINT FK_UTAKMICA_SUDENJE FOREIGN KEY (ID_UTAKMICA) REFERENCES UTAKMICA (ID)
, CONSTRAINT FK_SUDAC_SUDENJE FOREIGN KEY (ID_SUDAC) REFERENCES SUDAC (ID)
, CONSTRAINT FK_ULOGA_SUDENJE FOREIGN KEY (ID_ULOGA) REFERENCES ULOGASUCA (ID)
);
