CREATE TABLE MJESTO 
(
  PBR NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(40) NOT NULL 
, CONSTRAINT MJESTO_PK PRIMARY KEY (PBR) ENABLE 
);

CREATE TABLE RANGSUCA 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(20) NOT NULL 
, CONSTRAINT RANGSUCA_PK PRIMARY KEY (ID) ENABLE 
);

CREATE TABLE KLUB 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(30) NOT NULL 
, CONSTRAINT KLUB_PK PRIMARY KEY (ID) ENABLE 
);

CREATE TABLE VRSTAEKIPE 
(
  ID NUMBER(10) NOT NULL 
, UZRAST VARCHAR2(20) NOT NULL 
, SPOL VARCHAR2(10) NOT NULL 
, CONSTRAINT VRSTAEKIPE_PK PRIMARY KEY (ID) ENABLE 
);

CREATE TABLE EKIPA 
(
  ID NUMBER(10) NOT NULL 
, NAZIV VARCHAR2(20) 
, ID_VRSTA NUMBER(10) NOT NULL 
, ID_KLUB NUMBER(10) NOT NULL 
, CONSTRAINT EKIPA_PK PRIMARY KEY (ID) ENABLE 
, CONSTRAINT FK_VRSTA FOREIGN KEY (ID_VRSTA) REFERENCES VRSTAEKIPE (ID)
, CONSTRAINT FK_KLUB FOREIGN KEY (ID_KLUB) REFERENCES KLUB (ID)
);
