--brisanje svih redaka iz svih tablica
DELETE FROM SUDENJE;
DELETE FROM LISTA;
DELETE FROM SUDAC;
DELETE FROM UTAKMICA;
DELETE FROM NATJECANJE;
DELETE FROM EKIPA;
DELETE FROM VRSTAEKIPE;
DELETE FROM KLUB;
DELETE FROM MJESTO;
DELETE FROM RANGSUCA;
DELETE FROM ULOGASUCA;