--da bi mogli obrisati tablicu, moramo najprije obrisati strane ključeve
ALTER TABLE EKIPA DROP CONSTRAINT FK_VRSTA_EKIPA;
ALTER TABLE EKIPA DROP CONSTRAINT FK_KLUB_EKIPA;

ALTER TABLE NATJECANJE DROP CONSTRAINT FK_VRSTA_NATJECANJE;

ALTER TABLE UTAKMICA DROP CONSTRAINT FK_NATJECANJE_UTAKMICA;
ALTER TABLE UTAKMICA DROP CONSTRAINT FK_DOMACINI_UTAKMICA;
ALTER TABLE UTAKMICA DROP CONSTRAINT FK_GOSTI_UTAKMICA;

ALTER TABLE SUDAC DROP CONSTRAINT FK_RANG_SUDAC;
ALTER TABLE SUDAC DROP CONSTRAINT FK_PBR_STANOVANJA_SUDAC;
ALTER TABLE SUDAC DROP CONSTRAINT FK_PBR_RODJENJA_SUDAC;

ALTER TABLE LISTA DROP CONSTRAINT FK_SUDAC_LISTA;
ALTER TABLE LISTA DROP CONSTRAINT FK_NATJECANJE_LISTA;

ALTER TABLE SUDENJE DROP CONSTRAINT FK_UTAKMICA_SUDENJE;
ALTER TABLE SUDENJE DROP CONSTRAINT FK_SUDAC_SUDENJE;
ALTER TABLE SUDENJE DROP CONSTRAINT FK_ULOGA_SUDENJE;


--brisanje svih tablica
DROP TABLE SUDENJE;
DROP TABLE LISTA;
DROP TABLE SUDAC;
DROP TABLE UTAKMICA;
DROP TABLE NATJECANJE;
DROP TABLE EKIPA;
DROP TABLE VRSTAEKIPE;
DROP TABLE KLUB;
DROP TABLE MJESTO;
DROP TABLE RANGSUCA;
DROP TABLE ULOGASUCA;
